EPCT 10 - Bigger size for test order code
esaude/openmrs-module-poc pull request #17
Opened 2018-07-17 07:06 UTC by Guimino

using apache string leftpad to visualize test order sequence with 6 charaters

2018-07-17 07:10 UTC, Guimino commented
![](https://github.trello.services/images/mini-trello-icon.png) [Bigger size for test order code](https://trello.com/c/a6EGMJgJ/86-bigger-size-for-test-order-code)

2018-07-19 08:26 UTC, edrisse requested changes

2018-07-19 08:41 UTC, Guimino commented on api/src/main/java/org/openmrs/module/poc/testorder/service/TestOrderServiceImpl.java
> +	public static void main(final String[] args) {
removed unnecessary code, please review again.

2018-07-19 08:43 UTC, edrisse approved these changes

2018-07-19 08:43 UTC, merged